dataset:
  path: data/robomimic/square/processed_data96.hdf5
  rl_camera: agentview+robot0_eye_in_hand
  num_data: -1
use_wb: 1
num_epoch: 20
method: "arnn"
arnn_policy:
  encoder:
    feat_dim: 512
  cond_horizon: 2
  pred_horizon: 4
  noise_std: 0.1
  hidden_dim: 1024
lr: 1e-4
